export const shortcutMetadata = [
    { id: "nextImage", keys: ["ArrowRight", "d"], action: "Next Image", viewerOnly: true },
    { id: "previousImage", keys: ["ArrowLeft", "a"], action: "Previous Image", viewerOnly: true },
    { id: "nextChapter", keys: ["Alt+ArrowRight", "Alt+d"], action: "Next Chapter", viewerOnly: true },
    { id: "previousChapter", keys: ["Alt+ArrowLeft", "Alt+a"], action: "Previous Chapter", viewerOnly: true },
    { id: "firstChapter", keys: ["h"], action: "First Chapter", viewerOnly: true },
    { id: "lastChapter", keys: ["l"], action: "Last Chapter", viewerOnly: true },
    { id: "zoomIn", keys: ["+", "NumpadAdd"], action: "Zoom In", viewerOnly: true },
    { id: "zoomOut", keys: ["-", "NumpadSubtract"], action: "Zoom Out", viewerOnly: true },
    { id: "resetZoom", keys: ["=", "0", "Numpad0"], action: "Reset Zoom", viewerOnly: true },
    { id: "toggleFullscreen", keys: ["f"], action: "Toggle Fullscreen", viewerOnly: true },
    { id: "reloadChapter", keys: ["r"], action: "Reload Chapter", viewerOnly: true },
    { id: "toggleAutoScroll", keys: ["s"], action: "Toggle Auto Scroll", viewerOnly: true },
    {
        id: "toggleTheme",
        keys: ["t"],
        action: "Change Theme",
        viewerOnly: false,
        allowBeforeVerified: true,
    },
    { id: "openSettings", keys: ["Shift+S"], action: "Open Settings", viewerOnly: false },
    { id: "escape", keys: ["Escape"], action: "Return to Home / Close Modals", viewerOnly: false },
    { id: "cycleSidebarMode", keys: ["Ctrl+b"], action: "Cycle Sidebar Mode", viewerOnly: false },
];
