// Import all icons needed across the entire application
import {
    Check,
    CheckSquare,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronsLeft,
    ChevronsRight,
    ChevronsUpDown,
    CircleCheck,
    Database,
    Eye,
    EyeOff,
    HelpCircle,
    Home,
    Info,
    Laptop,
    Maximize,
    Menu,
    Minimize,
    Moon,
    PanelLeft,
    PanelLeftClose,
    PanelLeftOpen,
    Pencil,
    Plus,
    PlusCircle,
    Search,
    Settings,
    Sun,
    Trash2,
    Undo2,
    X,
    XSquare,
    ZoomIn,
    ZoomOut,
    createIcons,
} from "lucide";

export const AppIcons = {
    Check,
    CheckSquare,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronsLeft,
    ChevronsRight,
    ChevronsUpDown,
    CircleCheck,
    Database,
    Eye,
    EyeOff,
    HelpCircle,
    Home,
    Info,
    Laptop,
    Maximize,
    Menu,
    Minimize,
    Moon,
    PanelLeft,
    PanelLeftClose,
    PanelLeftOpen,
    Pencil,
    Plus,
    PlusCircle,
    Search,
    Settings,
    Sun,
    Trash2,
    Undo2,
    X,
    XSquare,
    ZoomIn,
    ZoomOut,
};

/** Renders Lucide icons by scanning elements with data-lucide attributes */
export function renderIcons() {
    createIcons({ icons: AppIcons });
}
