// Import all icons needed across the entire application
import {
    createIcons,
    PlusCircle,
    Plus,
    Pencil,
    Trash2,
    Menu,
    Home,
    Settings,
    ZoomIn,
    ZoomOut,
    Undo2,
    ChevronsUpDown,
    ChevronDown,
    ChevronsLeft,
    ChevronLeft,
    ChevronRight,
    ChevronsRight,
    CircleCheck,
    Check,
    CheckSquare,
    Search,
    PanelLeft,
    PanelLeftOpen,
    PanelLeftClose,
    Maximize,
    Minimize,
    X,
    Eye,
    EyeOff,
    Info,
    Sun,
    Moon,
    Laptop,
    Database,
    HelpCircle,
} from "lucide";

export const AppIcons = {
    PlusCircle,
    Plus,
    Pencil,
    Trash2,
    Menu,
    Home,
    Settings,
    ZoomIn,
    ZoomOut,
    Undo2,
    ChevronsUpDown,
    ChevronDown,
    ChevronsLeft,
    ChevronLeft,
    ChevronRight,
    ChevronsRight,
    CircleCheck,
    Check,
    CheckSquare,
    Search,
    PanelLeft,
    PanelLeftOpen,
    PanelLeftClose,
    Maximize,
    Minimize,
    X,
    Eye,
    EyeOff,
    Info,
    Sun,
    Moon,
    Laptop,
    Database,
    HelpCircle,
};

/** Renders Lucide icons by scanning elements with data-lucide attributes */
export function renderIcons() {
    createIcons({ icons: AppIcons });
}
